# 1. Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
 # Inside the container spec for api-gateway
      containers:
      - name: api-gateway
        image: devopsassignacr.azurecr.io/api-gateway:latest
        ports:
        - containerPort: 5000
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            # The CD pipeline will replace $(app_insights_ikey) with the actual key from the Variable Group
            value: "$(app_insights_ikey)" 
        # ... rest of the container spec
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi