# SecretProviderClass: Defines which secret to fetch from Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Use the AKS Node Identity granted access by Terraform
    userAssignedIdentityID: ""   # Leave blank for System Assigned Identity
    keyvaultName: "devopsassign-kv" # REPLACE with your actual Key Vault name
    objects: |
      array:
        - objectName: Demo-Secret-Key # The secret name from your Terraform
          objectType: secret
          objectVersion: "" # latest
  secretObjects:
    - secretName: app-secrets # The name of the Kubernetes Secret to be created
      type: Opaque
      data:
        - key: secretkey # Key in the Kubernetes Secret Manager
          objectName: Demo-Secret-Key # Name of the object in Key Vault